# Tf-idf example

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
texts = [
    "good movie", "not a good movie", "did not like", 
    "i like it", "good one"
]
# using default tokenizer in TfidfVectorizer
tfidf = TfidfVectorizer(min_df=2, max_df=0.5, ngram_range=(1, 2))
features = tfidf.fit_transform(texts)
pd.DataFrame(
    features.todense(),
    #get_feature_names() is deprecated; see source:
    #https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html
    columns=tfidf.get_feature_names_out()
)

   good movie      like     movie       not
0    0.707107  0.000000  0.707107  0.000000
1    0.577350  0.000000  0.577350  0.577350
2    0.000000  0.707107  0.000000  0.707107
3    0.000000  1.000000  0.000000  0.000000
4    0.000000  0.000000  0.000000  0.000000

document frequncies:

df(“good”) = 3 (docs 1, 2, 5)

df(“movie”) = 2 (docs 1, 2)

1-grams present in “good movie” are good and movie, each with TF = 1

ln(5/3) + ln(5/2)

In [7]:
# modifcations
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
texts = [
    "good breakfast", "not a good breakfast", "did not like breakfast", 
    "i liked it", "good pancakes"
]
# using default tokenizer in TfidfVectorizer
tfidf = TfidfVectorizer(
    ngram_range=(1,1),
    min_df=1,         
    max_df=1.0,      
    use_idf=True,
    smooth_idf=False, 
    norm=None,         
    sublinear_tf=False
)
features = tfidf.fit_transform(texts)
pd.DataFrame(
    features.todense(),
    #get_feature_names() is deprecated; see source:
    #https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html
    columns=tfidf.get_feature_names_out()
)

,breakfast,did,good,it,like,liked,not,pancakes
0,1.510826,0.000000,1.510826,0.000000,0.000000,0.000000,0.000000,0.000000
1,1.510826,0.000000,1.510826,0.000000,0.000000,0.000000,1.916291,0.000000
2,1.510826,2.609438,0.000000,0.000000,2.609438,0.000000,1.916291,0.000000
3,0.000000,0.000000,0.000000,2.609438,0.000000,2.609438,0.000000,0.000000
4,0.000000,0.000000,1.510826,0.000000,0.000000,0.000000,0.000000,2.609438